### ISSUE TITLE
range usage

### ISSUE THREAD

**Issue by frakman1** [voidloop/lifx-bash#1]
Thank you for providing this very useful and valuable library.

Could you please provide more examples using colour instead of just white? In particular, what are the valid ranges for the various parameters like hue,saturation,value,kelvin,duration and its units? I've tried various combinations of numbers but couldn't get any colour to show.

**Comment by voidloop** [comment]
Hi,
the valid ranges for the various parameters are the following: 
- hue: 0 - 65535
- saturation: 0 - 65535
- brightness: 0 - 65535
- kelvin: 2500 (warm) - 9000 (cool)

This information is also available on this page: http://lan.developer.lifx.com/v2.0/docs/light-messages#section-hsbk

Traditional hue scale goes from 1 to 360 so you need map these values from 0 - 65535. You can do this with this formula: (hue*65535)/360. 

Here more examples with colors:
- green: (120 \* 65535) / 360 = 21845 

```
echo -e $(./setcolor.sh 21845 65535 65535 3500 1000) | socat -u - udp-datagram:192.168.0.255:56700,broadcast
```
- red: (3 \* 65535) / 360 = 546

```
echo -e $(./setcolor.sh 546 65535 65535 3500 1000) | socat -u - udp-datagram:192.168.0.255:56700,broadcast
```
- blue: (240 \* 65535) / 360 = 43690

```
echo -e $(./setcolor.sh 43690 65535 65535 3500 1000) | socat -u - udp-datagram:192.168.0.255:56700,broadcast
```

The values of saturation and brightness go from 0 to 100 so the formula to map the scale is  (value \* 65535) / 100.

**Comment by frakman1** [comment]
Thank you Marco. That is a perfect answer and had everything I could possibly ask for!
